name: Build Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build packages
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e git+https://github.com/KitwareMedical/dicom-anonymizer.git#egg=dicom_anonymizer

    - name: Build software
      run: |
        mkdir tmp_dependencies
        pyinstaller --noconfirm --clean main.spec

    - name: Make installer
      run: |
        mkdir -p DICOMAnonymizer_ubuntu/usr/local/bin
        cp -r dist/DICOMAnonymizer DICOMAnonymizer_ubuntu/usr/local/bin
        dpkg-deb --build --root-owner-group DICOMAnonymizer_ubuntu
        cp -r DICOMAnonymizer_ubuntu.deb dist/DICOMAnonymizer-0.1.0-ubuntu.deb

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: ${{github.workspace}}/dist/DICOMAnonymizer-*
        if-no-files-found: error
